import "./globals.css";

import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";

import { Karla } from "next/font/google";

const karla = Karla({
  weight: ["400", "600", "800"],
  variable: "--font-karla",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-base-300">
      <body className={`${karla.className} antialiased`}>
        <NextTopLoader />
        {children}
      </body>
    </html>
  );
}
